// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateEmailAndPassword.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateEmailAndPassword = `-- name: UpdateEmailAndPassword :exec
UPDATE users
SET updated_at = NOW(),
email = $2,
hashed_password = $3
WHERE id = $1
`

type UpdateEmailAndPasswordParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

func (q *Queries) UpdateEmailAndPassword(ctx context.Context, arg UpdateEmailAndPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailAndPassword, arg.ID, arg.Email, arg.HashedPassword)
	return err
}
