// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upgUserChirpyRed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upgradeUserById = `-- name: UpgradeUserById :exec
UPDATE users
SET is_chirpy_red = TRUE,
updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpgradeUserById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, upgradeUserById, id)
	return err
}
